steps:
# Integration
# Install dependencies
- name: python
  entrypoint: pip
  args: [ "install", "-r", "requirements.txt", "--user" ]
# Run unit tests
- name: python
  entrypoint: python
  args: [ "-m", "pytest" ]
  id: 'test'
# Deployment
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --no-promote --version=dev']
  waitFor: ['test']
  id: 'deploy-main'
timeout: '1600s'
